website/music/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # /music/
    url(r'^$', views.index, name='index'),
    # /music/71/
    url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail')
]

website/website/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls'))
]

website/music/models.py
from django.db import models

# Create your models here.

from django.db import models

class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)

    def __str__(self):
        return self.album_title+"-"+self.artist



class Song(models.Model):
    album = models.ForeignKey(Album , on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    def __str__(self):
        return self.song_title

website/music/views.py
from django.http import Http404
from django.shortcuts import render
from .models import Album


def index(request):
    all_albums = Album.objects.all()
    return render(request, 'music/index.html',{'all_albums': all_albums})


def detail(request, album_id):
    try:
        album = Album.objects.get(pk=album_id)
    except Album.DoesNotExist:
        raise Http404("Album does not exist")
    return render(request, 'music/details.html', {'album': album})

website/music/templates/music/details.html
<img src="{{ album.album_logo }}">

<h1>{{ album.album_title }}</h1>
<h3>{{ album.artist }}</h3>


<ul>
    {% for song in album.song_set.all %}
        <li>{{ song.song_title }} - {{song.file_type}}</li>
    {% endfor %}
</ul>

website/music/templates/music/index.html
<h1>Here are all my albums</h1>
<ul>
    {% for album in all_albums %}
    <li><a href="/music/{{ album.id }}/">{{ album.album_title }}</a></li>
    {% endfor %}
</ul>